import type { Auction } from "@/types/auction";

export const AUCTIONS: Auction[] = [
  {
    id: "ax-001",
    name: "Nike Dunk Low Panda",
    brand: "Nike",
    category: "Sneakers",
    size: "US 9",
    condition: "DS",
    status: "live",
    currentBid: 18500,
    minIncrement: 300,
    endsIn: 42,
    watchers: 21,
    image: "👟",
    imageHue: "bg-stone-200",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-002",
    name: "Yeezy 350 V2 Beluga",
    brand: "adidas",
    category: "Sneakers",
    size: "US 9.5",
    condition: "VNDS",
    status: "live",
    currentBid: 25200,
    minIncrement: 500,
    endsIn: 72,
    watchers: 34,
    image: "👟",
    imageHue: "bg-yellow-100",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-003",
    name: "Supreme Box Logo Hoodie",
    brand: "Supreme",
    category: "Streetwear",
    size: "Size L",
    condition: "DS",
    status: "live",
    currentBid: 31000,
    minIncrement: 500,
    endsIn: 135,
    watchers: 18,
    image: "🧥",
    imageHue: "bg-red-100",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-004",
    name: "Air Jordan 4 University Blue",
    brand: "Jordan",
    category: "Sneakers",
    size: "US 10",
    condition: "DS",
    status: "live",
    currentBid: 28750,
    minIncrement: 500,
    endsIn: 151,
    watchers: 12,
    image: "👟",
    imageHue: "bg-sky-100",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-005",
    name: "Off-White Air Jordan 1",
    brand: "Jordan",
    category: "Sneakers",
    size: "US 9",
    condition: "DS",
    status: "live",
    currentBid: 28000,
    minIncrement: 500,
    endsIn: 213,
    watchers: 16,
    image: "👟",
    imageHue: "bg-stone-100",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-006",
    name: "Adidas Gazelle Bold Pink",
    brand: "adidas",
    category: "Sneakers",
    size: "UK 7",
    condition: "DS",
    status: "live",
    currentBid: 9800,
    minIncrement: 200,
    endsIn: 260,
    watchers: 9,
    image: "👟",
    imageHue: "bg-pink-100",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-007",
    name: "Air Jordan 1 Mocha",
    brand: "Jordan",
    category: "Sneakers",
    size: "US 9",
    condition: "DS",
    status: "live",
    currentBid: 16500,
    minIncrement: 300,
    endsIn: 7533,
    watchers: 48,
    image: "👟",
    imageHue: "bg-amber-100",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-008",
    name: "Travis Scott Cactus Jack Hoodie",
    brand: "Cactus Jack",
    category: "Streetwear",
    size: "Size M",
    condition: "DS",
    status: "live",
    currentBid: 48000,
    minIncrement: 1000,
    endsIn: 1800,
    watchers: 56,
    image: "🧥",
    imageHue: "bg-stone-200",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-009",
    name: "New Balance 550 White Green",
    brand: "New Balance",
    category: "Sneakers",
    size: "US 10",
    condition: "DS",
    status: "upcoming",
    currentBid: 0,
    minIncrement: 200,
    endsIn: 86400,
    watchers: 6,
    image: "👟",
    imageHue: "bg-emerald-50",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-010",
    name: "Bape Shark Full Zip Hoodie",
    brand: "Bape",
    category: "Streetwear",
    size: "Size L",
    condition: "VNDS",
    status: "upcoming",
    currentBid: 0,
    minIncrement: 500,
    endsIn: 129600,
    watchers: 14,
    image: "🧥",
    imageHue: "bg-blue-100",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-011",
    name: "Air Jordan 4 Bred Reimagined",
    brand: "Jordan",
    category: "Sneakers",
    size: "US 10",
    condition: "DS",
    status: "sold",
    currentBid: 32800,
    minIncrement: 0,
    endsIn: 0,
    watchers: 0,
    image: "👟",
    imageHue: "bg-zinc-200",
    verified: true,
    seller: "HYPE India Store",
  },
  {
    id: "ax-012",
    name: "Yeezy Slide Pure",
    brand: "adidas",
    category: "Sneakers",
    size: "US 10",
    condition: "DS",
    status: "sold",
    currentBid: 12500,
    minIncrement: 0,
    endsIn: 0,
    watchers: 0,
    image: "👟",
    imageHue: "bg-stone-100",
    verified: true,
    seller: "HYPE India Store",
  },
];

export const getAuctionById = (id: string): Auction | undefined =>
  AUCTIONS.find((a) => a.id === id);

/** Slugify an auction name (kebab-case, lowercased, ASCII only). */
export const slugify = (s: string): string =>
  s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

export const getAuctionSlug = (a: Auction): string => `${a.id}-${slugify(a.name)}`;

export const getAuctionBySlug = (slug: string): Auction | undefined =>
  AUCTIONS.find((a) => getAuctionSlug(a) === slug);

export const getAllAuctionSlugs = (): string[] => AUCTIONS.map(getAuctionSlug);

export const getLiveAuctions = (): Auction[] => AUCTIONS.filter((a) => a.status === "live");
export const getUpcomingAuctions = (): Auction[] =>
  AUCTIONS.filter((a) => a.status === "upcoming");
export const getSoldAuctions = (): Auction[] => AUCTIONS.filter((a) => a.status === "sold");
