import { Auction } from '@/types/auction';

export const mockAuctions: Auction[] = [
  {
    id: '1',
    title: 'Vintage Swiss Chronograph 1960s',
    description: 'Rare vintage chronograph with original leather strap',
    image: 'https://images.unsplash.com/photo-1523170335684-f242b73547e8?w=500&h=500&fit=crop',
    currentBid: 2500,
    startingBid: 1500,
    endTime: new Date(Date.now() + 48 * 60 * 60 * 1000),
    status: 'live',
    seller: {
      id: 'seller-1',
      name: 'Luxury Collectibles',
      verified: true,
    },
    totalBids: 12,
    category: 'Watches',
    featured: true,
    views: 234,
  },
  {
    id: '2',
    title: 'Art Deco Diamond Ring',
    description: 'Exquisite 2-carat diamond in 18K white gold setting',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=500&fit=crop',
    currentBid: 5200,
    startingBid: 3000,
    endTime: new Date(Date.now() + 72 * 60 * 60 * 1000),
    status: 'live',
    seller: {
      id: 'seller-2',
      name: 'Fine Jewelry Auctions',
      verified: true,
    },
    totalBids: 28,
    category: 'Jewelry',
  },
  {
    id: '3',
    title: 'Original Oil Painting by Modernist',
    description: 'Abstract composition, oil on canvas, 1970s',
    image: 'https://images.unsplash.com/photo-1578062097299-72ba2483f942?w=500&h=500&fit=crop',
    currentBid: 8500,
    startingBid: 5000,
    endTime: new Date(Date.now() + 36 * 60 * 60 * 1000),
    status: 'live',
    seller: {
      id: 'seller-3',
      name: 'Contemporary Art House',
      verified: true,
    },
    totalBids: 16,
    category: 'Art',
    featured: true,
    views: 512,
  },
  {
    id: '4',
    title: 'Rare First Edition Book Collection',
    description: 'Set of 3 signed first editions from acclaimed authors',
    image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=500&h=500&fit=crop',
    currentBid: 1800,
    startingBid: 1000,
    endTime: new Date(Date.now() + 24 * 60 * 60 * 1000),
    status: 'live',
    seller: {
      id: 'seller-4',
      name: 'Literary Treasures',
      verified: true,
    },
    totalBids: 9,
    category: 'Books',
  },
  {
    id: '5',
    title: 'Antique Porcelain Vase',
    description: 'Qing Dynasty hand-painted porcelain vase, pristine condition',
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=500&h=500&fit=crop',
    currentBid: 3200,
    startingBid: 2000,
    endTime: new Date(Date.now() + 60 * 60 * 60 * 1000),
    status: 'upcoming',
    seller: {
      id: 'seller-5',
      name: 'Eastern Antiquities',
      verified: true,
    },
    totalBids: 0,
    category: 'Antiques',
  },
  {
    id: '6',
    title: 'Designer Leather Handbag Limited Edition',
    description: 'Iconic designer bag, limited production run, never used',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=500&fit=crop',
    currentBid: 2100,
    startingBid: 1200,
    endTime: new Date(Date.now() + 18 * 60 * 60 * 1000),
    status: 'live',
    seller: {
      id: 'seller-6',
      name: 'Luxury Fashion House',
      verified: true,
    },
    totalBids: 14,
    category: 'Fashion',
  },
  {
    id: '7',
    title: 'Vintage Camera Collection',
    description: 'Set of 5 professionally restored vintage cameras',
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=500&h=500&fit=crop',
    currentBid: 1600,
    startingBid: 900,
    endTime: new Date(Date.now() - 12 * 60 * 60 * 1000),
    status: 'ended',
    seller: {
      id: 'seller-7',
      name: 'Photography Collectibles',
      verified: true,
    },
    totalBids: 22,
    category: 'Photography',
  },
  {
    id: '8',
    title: 'Gold Sovereign Coin Set',
    description: '10 piece rare gold sovereign collection, dated 1800s-1900s',
    image: 'https://images.unsplash.com/photo-1625491927637-c55f7f02b5d1?w=500&h=500&fit=crop',
    currentBid: 4500,
    startingBid: 3500,
    endTime: new Date(Date.now() + 96 * 60 * 60 * 1000),
    status: 'live',
    seller: {
      id: 'seller-8',
      name: 'Numismatic Experts',
      verified: true,
    },
    totalBids: 19,
    category: 'Coins',
    featured: true,
  },
];

export const mockStats = {
  totalAuctions: 1234,
  activeAuctions: 342,
  totalBids: 45678,
  uniqueBidders: 8925,
};

export const mockCategories = [
  'Watches',
  'Jewelry',
  'Art',
  'Books',
  'Antiques',
  'Fashion',
  'Photography',
  'Coins',
  'Cars',
  'Collectibles',
];
